services:
  backend:
    build: backend
    restart: always
    container_name: golang_server
    ports:
      - "8080:8080"
    networks:
      - localnet
    environment:
      CONFIG_PATH: ${CONFIG_PATH}
    volumes:
      - ./config:/config

  proxy:
    image: nginx:1.27.3-alpine
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    networks:
      - localnet
    depends_on:
      - backend

networks:
  localnet:
    driver: bridge
