services:
  backend:
    build: backend
    restart: always
    container_name: golang_server
    expose:
      - 8080
    networks:
      - localnet
    environment:
      CONFIG_PATH: ${CONFIG_PATH}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./config:/config
    depends_on:
      - dbase

  dbase:
    image: postgres:15
    restart: always
    container_name: dbase_server
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - 5432
    networks:
      - localnet
    volumes:
      - ./storage:/var/lib/postgresql/data

  proxy:
    image: nginx:1.27.3-alpine
    restart: always
    container_name: proxy_server
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    networks:
      - localnet
    depends_on:
      - backend

volumes:
  storage:


networks:
  localnet:
    driver: bridge
