services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.migrator
    restart: always
    container_name: golang_server
    ports:
      - "8080:8080"
    networks:
      - localnet
    environment:
      CONFIG_PATH: ${CONFIG_PATH}
      MIGRATIONS_PATH: ${MIGRATIONS_PATH}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./config:/config
      - ./migrations:/migrations
    depends_on:
      dbase:
        condition: service_healthy

  dbase:
    image: postgres:15
    restart: always
    container_name: dbase_server
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
    networks:
      - localnet
    volumes:
      - ./storage:/var/lib/postgresql/data

volumes:
  storage:
    driver: local

networks:
  localnet:
    driver: bridge
