# Используем базовый образ
FROM golang:1.22.2-alpine

WORKDIR /app

# Копируем и загружаем зависимости
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходный код и собираем приложение
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /migrator /app/cmd/migrator/main.go

# Открываем порт
EXPOSE 8080

# Запуск приложения
CMD /migrator --migrations-path=${MIGRATIONS_PATH}